/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as ItemsNewRouteImport } from './routes/items_.new'
import { Route as ItemsIdRouteImport } from './routes/items_.$id'
import { Route as ArticlesNewRouteImport } from './routes/articles_.new'
import { Route as ArticlesSlugRouteImport } from './routes/articles_.$slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/items_/new',
  path: '/items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items_/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles_/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles_/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/new': typeof ArticlesNewRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
  '/people/$id': typeof PeopleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/new': typeof ArticlesNewRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
  '/people/$id': typeof PeopleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/articles_/$slug': typeof ArticlesSlugRoute
  '/articles_/new': typeof ArticlesNewRoute
  '/items_/$id': typeof ItemsIdRoute
  '/items_/new': typeof ItemsNewRoute
  '/people/$id': typeof PeopleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/items'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/articles/$slug'
    | '/articles/new'
    | '/items/$id'
    | '/items/new'
    | '/people/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/items'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/articles/$slug'
    | '/articles/new'
    | '/items/$id'
    | '/items/new'
    | '/people/$id'
  id:
    | '__root__'
    | '/'
    | '/items'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/articles_/$slug'
    | '/articles_/new'
    | '/items_/$id'
    | '/items_/new'
    | '/people/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsNewRoute: typeof ItemsNewRoute
  PeopleIdRoute: typeof PeopleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/new': {
      id: '/items_/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/$id': {
      id: '/items_/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/new': {
      id: '/articles_/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/$slug': {
      id: '/articles_/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  ItemsIdRoute: ItemsIdRoute,
  ItemsNewRoute: ItemsNewRoute,
  PeopleIdRoute: PeopleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
