/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksNewRouteImport } from './routes/works_.new'
import { Route as WorksIdRouteImport } from './routes/works_.$id'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as ArticlesNewRouteImport } from './routes/articles_.new'
import { Route as ArticlesSlugRouteImport } from './routes/articles_.$slug'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksNewRoute = WorksNewRouteImport.update({
  id: '/works_/new',
  path: '/works/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIdRoute = WorksIdRouteImport.update({
  id: '/works_/$id',
  path: '/works/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles_/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles_/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/works': typeof WorksRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/new': typeof ArticlesNewRoute
  '/people/$id': typeof PeopleIdRoute
  '/works/$id': typeof WorksIdRoute
  '/works/new': typeof WorksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/works': typeof WorksRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/new': typeof ArticlesNewRoute
  '/people/$id': typeof PeopleIdRoute
  '/works/$id': typeof WorksIdRoute
  '/works/new': typeof WorksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/works': typeof WorksRoute
  '/articles_/$slug': typeof ArticlesSlugRoute
  '/articles_/new': typeof ArticlesNewRoute
  '/people/$id': typeof PeopleIdRoute
  '/works_/$id': typeof WorksIdRoute
  '/works_/new': typeof WorksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/works'
    | '/articles/$slug'
    | '/articles/new'
    | '/people/$id'
    | '/works/$id'
    | '/works/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/works'
    | '/articles/$slug'
    | '/articles/new'
    | '/people/$id'
    | '/works/$id'
    | '/works/new'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/works'
    | '/articles_/$slug'
    | '/articles_/new'
    | '/people/$id'
    | '/works_/$id'
    | '/works_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WorksRoute: typeof WorksRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  PeopleIdRoute: typeof PeopleIdRoute
  WorksIdRoute: typeof WorksIdRoute
  WorksNewRoute: typeof WorksNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works_/new': {
      id: '/works_/new'
      path: '/works/new'
      fullPath: '/works/new'
      preLoaderRoute: typeof WorksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works_/$id': {
      id: '/works_/$id'
      path: '/works/$id'
      fullPath: '/works/$id'
      preLoaderRoute: typeof WorksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/new': {
      id: '/articles_/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/$slug': {
      id: '/articles_/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WorksRoute: WorksRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  PeopleIdRoute: PeopleIdRoute,
  WorksIdRoute: WorksIdRoute,
  WorksNewRoute: WorksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
